# http://localhost:8080/h2-console

spring.datasource.url=jdbc:h2:mem:bibliothequedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.defer-datasource-initialization=true
